### ISSUE TITLE
server binding to * instead of localhost

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#104]
Running the server, it used to bind to localhost, but I believe after switching to the module version (or could be other things like just a code update or nodejs update), it is binding to all interfaces, which is undesirable.

Starting server like so:

node node_modules/\@cdot/xanado/bin/server.js --config /home/nodejs/Xanado/config.json;

Here you can see it is binding globally on all interfaces:

$ ss -lt |grep 9093
LISTEN 0      511                *:9093                   *:*

Is there any way to change this behavior?  I know there used to be a config setting for URI, but don't see it anymore.  Thanks

**Comment by cdot** [comment]
This probably happened when HTTPS support was added. Express by default binds all interfaces. Parameters to `listen` should cure this: see `src/server/Server.js:187` and [the Express documentation](https://expressjs.com/en/api.html#app.listen)

**Comment by cdot** [comment]
Changed it to bind to localhost by default, and added a "Host" config parameter.

**Comment by cdot** [comment]
I reverted binding to localhost by default as it breaks docker. I've improved the doc on how to override the default host, so hopefully no-one gets caught by this again.
