### ISSUE TITLE
server not obeying config file

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#105]
Starting server like so:

node node_modules/\@cdot/xanado/bin/server.js --config /home/nodejs/Xanado/config.json

with config.json:

{
    "port": "9093",
    "game_defaults": {
        "edition": "English_Scrabble",
        "dictionary": "scrabble7",
        "timerType": "Turn timer",
        "timerAllowed": "13",
        "challengePenalty": "Miss next turn"
    },
    "auth": {
        "session_secret": "foobar",
        "db_file" : "passwd.json"
    }
}

when games are created, however, they do not have these defaults.  In fact, I'm not even sure where the defaults are coming from as I hardcoded some of these (like timerAllowed) in the src/game/Game.js and it still shows other values.  Where are these values coming from and how do I change them?  Thanks

![create_game](https://github.com/cdot/Xanado/assets/20344426/edc7d374-1a13-4187-ab04-445c2fed8506)

**Comment by cdot** [comment]
You have a typo in your `config.json`; it should be `timeAllowed` not `timerAllowed`.

For a default dictionary to be selectable in the interface it has to exist in the `dictionaries` folder and, if you are running standalone, has to be listed in `dictionaries/index.json`. Even if it is listed the the defaults, it won't appear in the interface unless it exists.

There are a couple of routes you can use to check what the server knows. Defaults can be checked using `curl http://localhost:9093/defaults/game`. , and dictionaries using `curl http://localhost:9093/dictionaries/`

The dictionary dropdown was getting (incorrectly) overwritten in code.

**Comment by cdot** [comment]
I *think* this has resolved the issue, but need confirmation.
