### ISSUE TITLE
Webpack fails to load some config

### ISSUE THREAD

**Issue by tgmgroup** [cdot/Xanado#111]
First of all, thanks for all the development work on this!

I'm trying to run using npm install / run build, but it fails to build with some webpack issue. Somehow it can't find the webpack files?

Here's the output: 

```
> @cdot/xanado@3.1.4 build
> webpack --node-env production -c build/wp_sa_games.js; webpack --node-env production -c build/wp_sa_game.js; webpack --node-env production -c build/wp_cl_games.js; webpack --node-env production -c build/wp_cl_game.js

[webpack-cli] Failed to load 'C:\...\build\wp_sa_games.js;' config
[webpack-cli] Error: Cannot find module 'C:\...\build\wp_sa_games.js;'
Require stack:
- C:\...node_modules\webpack-cli\lib\webpack-cli.js
- C:\...\node_modules\webpack-cli\lib\bootstrap.js
- C:\...\node_modules\webpack-cli\bin\cli.js
- C:\Portable\...\node_modules\webpack\bin\webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at WebpackCLI.tryRequireThenImport (C:\...\node_modules\webpack-cli\lib\webpack-cli.js:223:30)     
    at loadConfigByPath (C:\...\node_modules\webpack-cli\lib\webpack-cli.js:1406:38)
    at C:\...\node_modules\webpack-cli\lib\webpack-cli.js:1460:88
    at Array.map (<anonymous>)
    at WebpackCLI.loadConfig (C:\...\node_modules\webpack-cli\lib\webpack-cli.js:1460:68)
    at WebpackCLI.createCompiler (C:\...\node_modules\webpack-cli\lib\webpack-cli.js:1781:33) {        
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\...\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\...\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\...\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\...\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
```

I've found that webpack seems to have similar errors for a lot of people, tried a few things, but nothing worked. I'm using the latest version of node and npm. Could you suggest anything to help me to get it to work?

**Comment by tgmgroup** [comment]
Running the docker image, I also get this:
`internal/modules/cjs/loader.js:818

  throw err;

  ^


Error: Cannot find module '/app/server.js'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

    at internal/main/run_main_module.js:17:47 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}

internal/modules/cjs/loader.js:818

  throw err;

  ^


Error: Cannot find module '/app/server.js'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

    at internal/main/run_main_module.js:17:47 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}`

**Comment by cdot** [comment]
I can't reproduce this on Linux, either on with node 19.3.0 or the Hydrogen LTS (18.18.1) using `npm run build` . I suspect there's something not right about your environment. What versions of npm/node/webpack are you using? ("Latest versions" is no good, as they differ between platforms.) What directory are you in when you issue the `npm run build` command? Unfortunately I don't have a copy of Windows to test it myself.

**Comment by tgmgroup** [comment]
Thanks for the response. I was thinking Windows was a problem, too. The dev-build and dev-server seem to work, though, so I'm working off of that, although I'd like to get the docker image working. I had issues with node and npm when I first started using your fork two years ago, too, but they were fixed when I updated node, and this time it's not being fixed.

My environment is:
- running in the Xanado directory
- node: v20.8.0
- npm: 10.1.0
- webpack@5.88.2
- webpack-cli@5.1.4

If you don't have windows, I'll just run it using the development build and try to figure out what's wrong later on.

**Comment by cdot** [comment]
Just tried this (on a Windows 10 VM)
- installed nvm-windows
- nvm install 20.8.0
- nvm use 20.8.0
- npm install @cdot/xanado
- xanado.cmd

Server started up fine. Few problems running in Edge but that's another matter.

**Comment by cdot** [comment]
Should work now.

**Comment by tgmgroup** [comment]
Pretty amazing work. Thanks for debugging this!
