### ISSUE TITLE
Running the docker image, I also get this:

### ISSUE THREAD

**Issue by cdot** [cdot/Xanado#112]
Issue reported by @tgmgroup

              Running the docker image, I also get this:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/app/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

_Originally posted by @tgmgroup in https://github.com/cdot/Xanado/issues/111#issuecomment-1758511041_

**Comment by cdot** [comment]
No idea what causes this; the docker image works fine on Linux, and I can't get docker to install on my Windows 10 VM.

**Comment by unarmedpawn** [comment]
I also get this on linux.  Is there a work around?

**Comment by tgmgroup** [comment]
It probably was the semicolon thing in #111. After he updates it, it might work.

**Comment by cdot** [comment]
I doubt it's related to the semicolon; the docker image doesn't use any of the build, it runs direct from sources.

@unarmedpawn, what rev of docker are you using? I have 24.0.2 on Ubuntu 22.04.1 and it works fine.

**Comment by unarmedpawn** [comment]
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

**Comment by cdot** [comment]
I am far from being a docker expert. I may well be comparing apples with oranges.

**Comment by cdot** [comment]
I still haven't been able to reproduce the reported stack trace, but I found a few problems with the workflow that meant it hadn't been build in aeons. I rebuilt it, and am closing this - if there's still a problem, please open a new issue.

**Comment by unarmedpawn** [comment]
the latest docker image runs again. thanks for the great app.

**Comment by tgmgroup** [comment]
Thanks!
