### ISSUE TITLE
Build docker image on each release

### ISSUE THREAD

**Issue by tambetliiv** [cdot/Xanado#113]
Latest tagged docker image is `3.1.0` but latest released version is `3.1.5`.

Please configure pipeline to build docker image on every release.

**Comment by cdot** [comment]
I thought I had...

**Comment by tambetliiv** [comment]
At least they are not listed https://github.com/cdot/Xanado/pkgs/container/xanado/versions?filters%5Bversion_type%5D=tagged

**Comment by cdot** [comment]
The "master" build is the latest. Not sure what I should be doing to tag the docker image more meaningfully, I will look into it.

**Comment by cdot** [comment]
This appears to be working now, at least 3.1.6 is listed on the linked page. No feedback from poster, so closing.
