### ISSUE TITLE
swap tiles on rack when you release one tile over another

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#114]
Wondering if you could make it easier to rearrange letter on the rack by swapping tiles when you release a letter over another one.  It is a little painful now to arrange things.  So, for example, if you had "ABC" on the rack and you dragged the C over the A, it would become "CBA". That way you don't have to micromanage the open tile as much.

**Comment by cdot** [comment]
Agreed, it's a bit painful. Modified as suggested.
