### ISSUE TITLE
another game button carries over challenge penalty

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#115]
When a player challenges the last play of the game and loses, thereby normally losing their next turn, when you hit the "another game" button and move to the next game, the player misses their first turn in the next game even though they should start afresh without the penalty.

**Comment by cdot** [comment]
When another game is started, a new game object is created. A new set of Player objects are created using the Player objects from the previous game as a template. The `missNextTurn` state is getting inherited that way :-(
