### ISSUE TITLE
floating tiles in new rack swap feature

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#116]
Thanks for adding the letter swap feature!  It works great for the most part.  We did notice, however, that sometimes letters can get caught floating in limbo if you release in the wrong spot.  For example, if you take a letter and move it slightly up and to the right, you can get a bunch of letters that can no longer be moved until you refresh.  An example below:

![floating](https://github.com/cdot/Xanado/assets/20344426/217a46a1-118f-45e8-88c9-4586794d65cb)

**Comment by cdot** [comment]
That looks like a silly bug I fixed after I first built the release - I suspect you grabbed 3.1.6 before I rebuilt it with the fix. Try re-downloading the 3.1.6 files; if you are able to reproduce the problem, then open the developer toolkit and let me know what the stack trace says.

**Comment by pkolano** [comment]
ok, must have just been bad timing as it works now.  thanks!
