### ISSUE TITLE
accept game messed up when person has lost their turn

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#120]
In a recent game, if a player is after the person who goes out, but had previously challenged so lost their turn, no accept game is available to the player after and the game continues with the next player even though a player went out and has no tiles.  You can see in this screenshot, two people have zero tiles:

![doublezero](https://github.com/cdot/Xanado/assets/20344426/c0ce8223-7fef-4143-8a47-d8d88a4f9311)

**Comment by cdot** [comment]
Let's make sure I understand this. Given your example, the sequence was as follows:
# You challenge and fail, so lose your next turn
# Joe plays, does not go out
# John plays, and goes out
# You are skipped because of your lost turn
# Joe is not offered "Accept last move", but in the example has played and gone out too.
Is that correct?

**Comment by pkolano** [comment]
The sequence was Joe played (but still had tiles left) and I challenged and lost.  Then John played and went out.  At that point, I was the next player, but it would not let me accept, which is the issue.  After that point, it was broken.  It then skipped to Joe who (just to be funny) played his final tiles even though the game should have been over.  At that point, the game could not be ended as even when accept game showed for John after Joe's turn that he should have never had, it didn't do anything.

**Comment by cdot** [comment]
The UI presents the "Accept last move" button when the last player has an empty rack. However the last player in this case is Paul, who doesn't have an empty rack. So the condition ought to be "if ANY player has an empty rack".

**Comment by cdot** [comment]
Should be OK now.
