### ISSUE TITLE
non-enforcing timer mode and timer legibility

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#13]
Wondering if you could add an additional timer mode where the timer is more of a "soft timer" that indicates time remaining but doesn't cause the player to lose a turn.  In our family, we play with a timer, but it's not strictly enforced and more of a "play as soon as you can" when it expires.  We could of course just set the timer higher, but would be nice to have a mode where it is notification only.

Also, the current timer is almost invisible when it's black text on green, and then a little distracting when it starts flickering.  Was thinking maybe a different colored box next to the letter rack of similar font size might be more visible.  I personally find the flickering a little distracting so was thinking just a solid number countdown might work better.  Anyway, just a thought.  Thanks for your work on this.

**Comment by cdot** [comment]
The distracting nature of the time was a deliberate design choice, as we sometimes play "lightning scrabble" where the pressure of the flashing timer is part of the game! There are several different timer scenarios, beside lightning scrabble and your soft timer - competition scrabble, for example, has a game time like a chess clock, where the cumulative time for a game is what counts, rather than the time taken for an individual move. Defining and implementing different timer strategies is a job for the future ;-)

**Comment by pkolano** [comment]
I think if you put a timer box in between the letter rack and the take back/shuffle buttons in mm:ss or sss format, then I could live with the blinking. :)  Anyway, great job on this, will try out for real with the family in a few days

**Comment by cdot** [comment]
I'd be happy to entertain a PR that styles the timer more attractively (and perhaps less distractingly!)

**Comment by cdot** [comment]
Currently the only timed game available limits each player to a fixed time to make a move. In club play, games are timed using a chess clock such that each player only gets a fixed time - usually 25 minutes - to make all of their moves. Exceed your allotted time and you’re penalized ten points for each minute over 25.

This can be approximated by a 2-minute time limit on individual plays, but it would be better if the total time clock were implemented. The clock time and penalty could be configured as part of the game setup.

**Comment by cdot** [comment]
The chess clock required all players to be able to see the time remaining on other players clocks, so I moved the time up to the player in the score block. Could be prettier, but OK for now. Two clocks modes now available, time per turn and time per game. Time per turn is still enforcing, time per game incurs a points penalty but you can ignore that by setting the game time really high.

**Comment by pkolano** [comment]
Thanks, looks pretty good.  Maybe could use a bold/beefier font and a little more separation from the score, but big improvement as is.  Also, the tick-high and tick-low look almost identical on my system.  I would still like to request a non-enforcing time per turn mode though.  Maybe you could have a setting dialog that is either "lose turn" or "point penalty" (or maybe a mode "time per turn with point penalty") and then playing with a point penalty of 0 would do what we want.  Thanks again for your work.  Game is really good now!
