### ISSUE TITLE
TypeError: Cannot read property 'stopTimer' of undefined

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#15]
Thanks, looks really good after your last updates. Did get the following random exception that killed the server.  Don't know the exact sequence of events that caused it.  I was deleting all the games (including finished), then started new game, then joined with two players, but not sure which thing was the trigger.

Player 'Paul' key 4k2ckkcfs9 connected
Started tick timer with -1 on the clock
playIfReady ae4a917aad2d68bc 4k2ckkcfs9
        next to play is Paul -1
<-*- connections [
  {
    name: 'Paul2',
    isRobot: false,
    connected: true,
    dictionary: undefined,
    key: '3x1vjuwcz4',
    score: 0,
    email: false,
    secondsToPlay: 0,
    gameKey: 'ae4a917aad2d68bc'
  },
  {
    name: 'Paul',
    isRobot: false,
    connected: true,
    dictionary: undefined,
    key: '4k2ckkcfs9',
    score: 0,
    email: false,
    secondsToPlay: -1,
    gameKey: 'ae4a917aad2d68bc'
  }
]
--> GET /history
--> GET /session
<-- 200 { name: 'Paul', provider: 'xanado', key: '4k2ckkcfs9' }
--> GET /session
<-- 200 { name: 'Paul2', provider: 'xanado', key: '3x1vjuwcz4' }
--> GET /history
--> GET /simple/active
--> GET /simple/all
--> GET /simple/active
Paul2 has timed out at 1647926292992
/home/nodejs/Xanado-master/js/game/Game.js:1210
                        passingPlayer.stopTimer();
                                      ^

TypeError: Cannot read property 'stopTimer' of undefined
    at Game.pass (/home/nodejs/Xanado-master/js/game/Game.js:1210:18)
    at Player._onTimeout (/home/nodejs/Xanado-master/js/game/Game.js:491:17)
    at Timeout._onTimeout (/home/nodejs/Xanado-master/js/game/Player.js:182:10)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by cdot** [comment]
I suspect this was a result of deleting a timed game while the timer was still running on it, though I can't reproduce it. When a game is deleted, the timers should be stopped; I see that is not happening, and when you delete a timed game between two players with both clients still open, the game will magically recreate itself when the timer expires. Definitely a bug, though somewhat obscure.

**Comment by cdot** [comment]
I stopped the timers before deleting the game. Hopefully this should cure this.
