### ISSUE TITLE
Passive watch game mode

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#17]
Would be nice to have a mode that allows others to watch a game in progress.  Sometimes we have extra people who just want to socialize on our voice chat, but not play or they get there late so wait until the current game is done.  I was thinking you could implement this without too much extra work by using the interface of a non-active player and just swapping the letter rack shown depending on the active player.  Could also have an option when creating the game of whether to allow watchers or not.  Anyway, not a high priority, but would be nice to have.

**Comment by cdot** [comment]
I agree; I did have this for a while, but it dropped off the radar for some reason. Also, I quite like the idea of having an independent non-playing referee who could decide in case of a challenge dispute in non-dictionary games. But as you say, not a high priority.

**Comment by cdot** [comment]
"Observe" button appears on games when not logged in. Will open an observer on the game.
