### ISSUE TITLE
Make the chat advisor an option instead of being on by default

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#18]
Right now, there is an "advisor" in the chat area that tells you if the word(s) you just played is not in the dictionary.  This gives an advantage to the player since they will then know if a word they weren't sure was good is good so can, for example, be pluralized later, or if a word they thought good was not, so similarly should not be pluralized later.  It would be better if it was a game option so this behavior could be disabled.  Thanks!

**Comment by cdot** [comment]
I'd rather go with the "soft" approach of telling everyone when a player has enabled advice.

**Comment by cdot** [comment]
Styled the messages so they are more "in your face"

**Comment by pkolano** [comment]
This is still an issue. To recreate, just play something that is not a word and the advisor will tell you it's not even if you haven't turned on the advisor using the "advise" keyword.  As mentioned, knowing a word played is invalid gives an advantage to the player who tried it.

**Comment by cdot** [comment]
My mistake, I didn't read your original post carefully enough. I thought you meant the advisor that is enabled with "advise" in the chat window, which tells you when a better move could have been played. But you are of course referring to the post-play dictionary check.
The only way a player could gain an advantage from this functionality if they were quick enough to hit "Take back" after the word has been played, but before the next player has challenged or committed their own play.
First observation is that official rule #5 of Scrabble from the Hasbro site says "No tile may be shifted or replaced after it has been played and scored", so the take back functionality is actually in violation of this rule.
If you don't have take back, there is no game play advantage from the dictionary check, though I suppose you could argue that correcting player vocabulary / spelling is against the spirit of the game?
My inclination is to optionally enable both these features - take back and dictionary check - at game creation time.

**Comment by cdot** [comment]
Predict score, Take back, and Check Dictionary are now all game options
