### ISSUE TITLE
Sign in help bubbles obscure text entry boxes

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#27]
When you use the sign in dialog, if you click the name field so it has focus, enter user name, and then hit tab as is normal in such boxes, the help bubble for the name field remains on the screen obscuring the password entry field.  Also, just for completeness, there is no help bubble for the password field in this part.  In the sign up dialog, tab brings up the next help bubble, but the bubble for the previous item is not removed, again obscuring the field you are on.

**Comment by pkolano** [comment]
This happens in other dialogs as well like the create game dialog.

**Comment by cdot** [comment]
It needs a bit of CSS fettling to reposition the tooltips. Right now it's using the JQuery default positioning, which I agree is pretty crap.

**Comment by cdot** [comment]
Further realisation: even if the tab button is pressed to move to the next field, if the mouse is left hovering over the previous field the tooltip for that field will still be displayed. So not actually a jQuery bug, just an undesireable feature.
