### ISSUE TITLE
chat messages push log box down off the screen

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#28]
To recreate, just enter a bunch of chat messages.  The log box will then be pushed down until you sometimes have to scroll the main window to see the bottom of it (this was in a 4 player game).  It would be better if maybe the chat and log boxes were preallocated some amount of space and the bottom of the log box was fixed to the bottom of the tile rack.  Believe this still leaves a reasonable amount of visible space in both chat and log boxes.  Thanks.

**Comment by cdot** [comment]
Chat messages now in log window, which is already big enough and scrollable
