### ISSUE TITLE
buggy anchor arrow behavior

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#30]
There is some strange behavior when you use the "anchor arrows" (i.e. when you click on the board and an arrow appears so you can type words onto the board).  If you put an anchor on the board and then click in the chat box, it doesn't clear the anchor so it starts typing both on the board and in the chat box.  It should clear when you click anything else.  I would also personally suggest a 3-stage click for the anchors so first is one direction, second is the other direction, third clears.  Right now, the only way to clear is to click on a letter in your letter rack.

You can also make the anchor appear in the letter rack itself. Further, if you choose the down anchor, it will start putting letters after the first one down on the board.  I would think you wouldn't want the anchors at all in the letter rack, although I suppose you could use it to arrange your rack quickly if just the right facing arrow was allowed.

**Comment by cdot** [comment]
Think it should be better now, though there may still be an issue with initiating "no mouse" operation.
