### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by exander77** [cdot/Xanado#35]
I did several changes locally:

1) Remove cloud files (js and css) libraries (have local copies.
2) Fix touch punch library so drag and drop of tiles works on Android.
3) Improve color scheme of the board.
4) Make layout in row for desktop and in column layout for Android and overall clean up layout.

![image](https://user-images.githubusercontent.com/2256039/164973110-6e217e31-6512-4424-aef8-8d77348b815d.png)

Would you accept something that big in a pull request?

**Comment by cdot** [comment]
Many thanks for your contribution! It's too much for a single pull request, as I'm not keen on the colour scheme / UI layout changes. But if we had a way to select themes interactively, I'd be delighted to have this layout as an alternative to the default.

I'm going to have a look at your changes for D&D on Android, that sounds really useful. I've also had verbal reports of problems under iOS/Safari that they might fix.

**Comment by exander77** [comment]
I will make a few pulls with this and you can examine them and merge what you see ok to merge.

**Comment by cdot** [comment]
Please be aware I just pushed a large commit that may impact your PRs!

**Comment by cdot** [comment]
Added a very basic theming system that you should be able to drop in your css to (after a few minor edits!) so that should help address 3 and 4. Would still like to know what you did for (2).

**Comment by cdot** [comment]
Pretty sure all these features have been implemented in latest code. I added an exander77 theme to reflect the colour scheme.
