### ISSUE TITLE
Extend predict score with verify words

### ISSUE THREAD

**Issue by exander77** [cdot/Xanado#38]
For causal play, it would be great to introduce a measure to prevent playing words which are not in the dictionary.
Player would be unable to play such words instead of waiting for being challenged.

It would also be great for playing with a computer.

**Comment by cdot** [comment]
It wouldn't be hard to do; the code for checking words is already there, though it runs asynchronously. It would need to be made a synchronous, and then if one of the words isn't found redirect to a "take back" command to force a play-again.

**Comment by exander77** [comment]
Great work. Already tested it.

I am currently building Czech dictionary and it is so hard, because there is no good Czech dictionary publically available. And it is super easy to hit a corner case when the dictionary is not good. I hit false positives (bot having words that should not be there) and false negatives (me not be able to make existing words because they are not in dictionary).

In Czech We mostly play PLUS variant which allows many word forms. I currently have 3 213 038 words for PLUS.
