### ISSUE TITLE
Server restart at the beginning of the game caused switch of first player

### ISSUE THREAD

**Issue by exander77** [cdot/Xanado#40]
I have started game with Robot and restarted server to apply updates, this caused the Robot to play instead of me as the first player, even though I was initially the first player.

**Comment by exander77** [comment]
It sounds like first player is not determined in the save file.

**Comment by exander77** [comment]
No, the problem is more severe. On server restart, Robot always makes a move.

**Comment by cdot** [comment]
Sounds like there may be a bug. After a restart, nothing should happen until somebody connects to a game, and then playIfReady should prepare the next player, which will almost never be the robot. HOWEVER server restarts should be rare (you are a special case, I admit ;-) ) so I don't see it as a big problem.

**Comment by exander77** [comment]
I think it happens when you connect to the game, but then the Robot automatically plays.

It should be rare, but currently it basically breaks all the games where is Robot.

**Comment by cdot** [comment]
There was a missing save()
