### ISSUE TITLE
weird behavior with another game button

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#44]
When a player has a failed challenge at the end of the game, the next game when started via another game button will skip their turn.  It should reset all lost turns.  Also with the another game, after every turn, you get server disconnected and are also logged out (i.e. the sign in button appears in the upper right of the game board screen).  Also, there is no timer in the new game even if original game was timed and main games screen still shows game as timed.  This used to work correctly a version or two back (I'm still on version right after you fixed the challenge functionality so maybe something broke with that).  Thanks!

**Comment by cdot** [comment]
Thanks Paul. Several issues here, as far as I understand it. To be honest, I don't understand the first report. When you start a new game via "Another Game" then the player order is randomised. So let's say we have players A, B and C, playing in that order. Player A clicks "Another Game". All players then select "Next game". The order in the new game is C, B, A. You are saying that after C and B have played, A is then skipped? Is that right?

Second issue; server connection has nothing to do with end game, there is something else going on there. Really need to run the server in "debug" mode and watch for what it said during game turnover.

Third issue: no new timer - I worked on timers a couple of weeks ago and thought I fixed all the issues 6e359f9 - could you update to the latest code, please, and if you are able to reproduce the problem, open a new issue.

**Comment by pkolano** [comment]
I believe the player that had a failed challenge to end the previous game is skipped in the new game, but will have to confirm that it is not just the first player skipped.

I will update before playing next time and try to remember to run in debug mode.  There were some exceptions I had saved in the server output (occurred at different times):

(node:11512) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token / in JSON at position 66                                                                                              at JSON.parse (<anonymous>)
    at /home/nodejs/Xanado-master/server.js:55:21                                                                                                                                              (Use `node --trace-warnings ...` to show where the warning was created)
(node:11512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

TypeError: this._debug is not a function
    at Player.tick (/home/nodejs/Xanado-master/js/game/Player.js:228:9)
    at Game.tick (/home/nodejs/Xanado-master/js/game/Game.js:999:11)
    at Timeout._onTimeout (/home/nodejs/Xanado-master/js/game/Game.js:1022:50)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) 

socket join error: TypeError: Cannot read property 'key' of undefined
    at Game.connect (/home/nodejs/Xanado-master/js/game/Game.js:929:38)
    at /home/nodejs/Xanado-master/js/server/Server.js:338:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by cdot** [comment]
I believe all the reported issues are resolved in the latest code.
