### ISSUE TITLE
weird end of game issues with challenges

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#45]
A couple times now, we've had some weirdness with challenges at the end of the game.  Near the end of the game, the game will sometimes just randomly end when you challenge.  Everyone will still have letters, but it will subtract letter amounts from all players.  I think the last time, everyone had less than 7 letters and the challenge succeeded.  Sorry don't have more info, but there is some underlying issue in end of game scenarios.  Thanks.

**Comment by cdot** [comment]
Are you running the ;latest code? Very difficult to debug unless I know what version you are running (I am using the git checkin ID to identify versions, because I'm too lazy / forgetful to update anything else :-( )

**Comment by pkolano** [comment]
sorry, I was not.  I was a couple versions behind, but I didn't think I saw anything in the commit comments that seemed relevant to this.  I will upgrade for next time and see if it still exists.

**Comment by cdot** [comment]
If you see this again please open a new issue with details of how to reproduce it.
