### ISSUE TITLE
latest version seems to have many issues

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#46]
I tried upgrading to latest version to see if the other bugs were still present, but it was unplayable.  The create game dialog had "object" instead of a value in the bottom option and showed up as "undefined" after the game was created.  When I joined a test game with the robot, my status never turned to green even after refresh.  While it allowed me to play, it never updated the board with the robot's plays.  The bottom tile rack had some weird extra green rectangle around it that matched the background but appeared "raised".  I guess it's possible I did something wrong while upgrading, but I reverted to an earlier commit (picked the one at https://github.com/cdot/Xanado/archive/6599ccb0ea5dc89727d385ab5d03eb467fee547a.zip) and everything worked fine again.  Thanks.

**Comment by cdot** [comment]
Tsk, yes, sorry, checkins got out of sequence. I'll fix it.

The extra green rectangle was deliberate, I was playing with CSS. I don't like it either so I'll kill it.
