### ISSUE TITLE
connected dot shows red

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#47]
In latest version, the link status dot next to the name shows red instead of green when connected, even after refresh.  It still works ok and updates for other player's moves, but just shows the wrong color.  To replicate, create new 2 player game with robot and open game.  Thanks.

**Comment by cdot** [comment]
Thanks - corrected in https://github.com/cdot/Xanado/commit/add63b168462e5c394ef830e045101b27ba47e75
