### ISSUE TITLE
Help with developer docs?

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#58]
I'm trying to understand the fundamentals of the source base and could use some high level outline of the code base.

Explanation of what "game" versus "games" are ? What is "the platform" or the browser platform? The best way to override/modify CSS so jquery doesn't win out? Help understanding the requirements for Facebook and Google login service to work?

I've tried offering documentation to other open source projects but mostly it is rejected. So perhaps the author(s) could touch on these few bits ?

We want to include the project into our video platform, for audience of matches and players to converse. Many thanks!!!

**Comment by cdot** [comment]
There is an existing high level view of the code in doc/README.md which might answer some of your questions.

"game" is the user interface (html/js) for the game board. "games" is the user interface to the database of all active and completed games, and is where you create new games (or change the options for existing games)

There are two platforms - the server platform, which runs an express server and handles most of the game logic, and the browser platform, which runs the "game" and "games" user interfaces.

The CSS is themable by creating a new subdirectory under css/ and overriding the defaults from the `css/defaults` directory. An example - exander77 - is given. The user interface is highly dependent on jquery and jquery UI. (This description is missing from doc/README.md and needs to be added.)

The Facebook and Google login services are implemented using a standard oauth2 interface. The services are configured in the config.json, as described in CONFIGURATION.md

**Comment by cdot** [comment]
No further questions forthcoming so I'm closing this as answered. I'm happy to answer any additional questions, or consider pull requests for additional / better documentation.

**Comment by gwhizoftv** [comment]
Thank you for the help! 
Regarding theming and overriding, the article from JQuery says there should be a file called theme.css, we don't seem to have. 
Regarding overriding, do we see the user changing all the sources to include the new css/<newfolder>common.css, etc ? Or how is the overriding intended to be implemented ? Many thanks.

**Comment by cdot** [comment]
Adding an alternate jQuery theme would require some (minimal) changes to the HTML to load the relevant jQuery css. For example,
```
    <link id="jQueryTheme" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet">
```
would load the default jQuery UI stylesheet. You can change this to load a different jquery UI stylesheet. I just never bothered to do it, as I override most of the visuals in the project-specific stylesheets.
---
Overriding of the local stylesheets does not require any code changes, you just add the overriding CSS files to a new subdirectoy of `css` and the UI will find them.
---
No, anonymous players is not something I ever intended to implement, but it wouldn't be hard to do, just a bit fiddly. Every player has to have a unique ID. This would have to be dynamically generated when an anonymous player joined a game. The ID could only last as long as the connection, so there would be no way for this player to drop out and rejoin the game later.

**Comment by gwhizoftv** [comment]
CC,

Thank you very much for the guidance. I was able to create a theme on
Jquery Themeroller and install it with your instructions.
Regarding Anonymous, our platform already has a user concept, so we could
certainly pass in the user's info into the create account logic,
if that would make any sense.

Many thanks for considering it!
