### ISSUE TITLE
Clone of repo to MacOS fails on two files

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#60]
When first running the clone of the repo, we see the following error:

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'js/browser/Game.js'
  'js/browser/game.js'
  'js/dawg/Compressor.js'
  'js/dawg/compressor.js'

**To Reproduce**
1. mkdir xanado; cd xanado
2. git clone 

Should cleanly clone the files into the current folder

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Monterey (case INsensitive O/S)
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] N/A

If there really are two files in the git somehow (not visible in the current repo here on github), one upper case and one lower case, just change the names slightly of those with lower case so they don't conflict.
If there is only one file, I suggest just change those two files to lower case.

**Comment by cdot** [comment]
Tsk. Thanks for picking this up - case insensitivity is very 1980's and easily forgotten. In general I employ the convention that files containing AMD modules that define classes and mixins are named with the name of the class or mixin (which always starts with an uppercase letter), while command-line programs and modules are lowercased, so case conflicts do occasionally occur. But as you say renaming the files is the way to go. `compressor.js` can be renamed `dictionary_compressor.js`, while `game.js` can be renamed `game_ui.js`.

I'm puzzled by the statement "not visible in the current repo here on github" https://github.com/cdot/Xanado/tree/master/js/browser shows all the files in that directory. I can't see how that would be related to case insensitity, but sometimes github can be a bit mysterious.

**Comment by cdot** [comment]
Should be fixed on master. I can't test, please close this issue if it's now OK.

**Comment by gwhizoftv** [comment]
Yes it seems to do nicely!

**Comment by gwhizoftv** [comment]
> I'm puzzled by the statement "not visible in the current repo here on github" https://github.com/cdot/Xanado/tree/master/js/browser shows all the files in that directory. I can't see how that would be related to case insensitity, but sometimes github can be a bit mysterious.

I could only see Game.js, not both game.js and Game.js. Apparently git can remember that game.js was changed to Game.js at one point?
