### ISSUE TITLE
Cannot try to login again after failing to log in

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#61]
If the first attempt to log in fails, clicking on Sign in again produces console errors and no login dialogu.

1. Clone the latest master, npm install
2. npm run server
3. Connect to the server in the browser
4. Click Sign in
5. Put in a username and password that are incorrect
6. Click on Sign in again
7. See no dialogue and errors

Should be able to try multiple times. Program /server should not crash

Console screenshot:
![Screen Shot 2022-10-03 at 12 52 14 PM](https://user-images.githubusercontent.com/94144702/193666568-ca90e145-7340-412a-9cb8-835238825aec.png)

And the code with the error:
` static open(dlg, options) {
      console.log("Static open", dlg, options);
      return new Promise(resolve => {
        requirejs([`browser/${dlg}`], Clas => {
          let inst = instances[dlg];
          if (inst) {
            if (options)
              Object.assign(inst.options, options);
            if (!inst.$dlg.dialog("isOpen")) {
              console.log("Open trigger", inst.options.game.key); <== error on 'key'
              // Options for a particular showing of the dialog
              for (const opt of ["height", "width", "title" ]) {
                if (typeof options[opt] !== "undefined")
                  inst.$dlg.dialog("option", opt, options.title);
              }
              inst.$dlg.dialog("open");
            }
          } else
            inst = instances[dlg] = new Clas(options);
          resolve(inst);
        });
      });
    }
  }

  return Dialog;
});`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Monterey
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
If I comment out the console.log() line with the error, it seems to be fine after that and allows multiple tries.

**Comment by cdot** [comment]
Sloppy. That was debugging from another session that should have been removed. Should be OK now.
