### ISSUE TITLE
Can the create new game open the game in the same window?

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#62]
In our UI, we open Xanado in a popout window from our main UI. As a result, if we create a new game, our popout window is closed, and a new tab is opened in the browser for the new game.
If there could be an option to open the game in the current window, that would be fantastic. I checked Game.js and the /create route in the server, but didn't catch the spot where the new window/tab is being created.

Many thanks!

**Comment by cdot** [comment]
I added an option in the settings dialog (and/or config.json)

**Comment by gwhizoftv** [comment]
This worked perfectly from config.json first try. Many thanks !!!
