### ISSUE TITLE
Our app shows empty divs for up to a few seconds before drawing the full UI of a game

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#63]
The first impression presented is that the app didn't load properly

**To Reproduce**
1. Change some css
2. Reload the page
3. See error
or
1. Close the browser window with Xanado
2. Reconnect to the server
3. Sign in
4. Join the game

**Expected behavior**
A spinner until the UI is ready to draw

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MaxOS Monterey
 - Browser [e.g. chrome, safari] Chrome

The delay varies a lot, I suppose based on pulling in resources.

**Comment by cdot** [comment]
Yes, there's a fair bit of resource loading going on. My server is pretty fast, so I never noticed it as an issue, but throttling the comms shows the problem. Really we should pack the resources using browserify or similar.
