### ISSUE TITLE
Typo in InvitePlayersDialogue crashes us

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#64]
When trying to invite a player via email, we get a crash after clicking the Invite submit button.

**To Reproduce**
1. Create a match with two people.
2. Open the match. Click Invite
3. Fill in the email and message and click invite.

**Expected behavior**
Send email or get socket connection error if email isn't configured

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Monterey
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
There is a typo on line 76 addCLoass-> addClass
after fixing this it runs fine.

**Comment by cdot** [comment]
This should have been picked up. I wish I could work out a way to test the UI that doesn't involve thousands of lines of extra code. Mocha is too clumsy. :-(
