### ISSUE TITLE
Advice is being calculated on new board

### ISSUE THREAD

**Issue by cdot** [cdot/Xanado#65]
**Describe the bug**
It appears that advice (from `advise` in the chat window) is being computed using the previous rack but the board after a sub-optimal play.

**To Reproduce**
1.Enter `advise` in the chat window
2. Play until the advisor generates incorrect advice.

**Expected behavior**
Advice should be based on the board as it was before the most recent play is applied.

This only applies to post facto advice regarding a possible better play, generated after the play is complete. `hint` is correct. As such it doesn't affect game play.

**Comment by gwhizoftv** [comment]
Crawford,

We tried playing a game, and found that after player1 placed the first
word, player 2 the next, then player 1 the third tying into P2's word, P2's
word disappeared from their display, seeing only P1's words on their
display.

Is this a known issue, or perhaps a setting?

Many thanks

**Comment by cdot** [comment]
Can you open a new issue for this, please don't re-use unrelated issues. If you can attach the game file, and if they are available, any console log messages in P1's browser. It would also be helpful to to know when you last did a `git pull` or updated your docker image.
