### ISSUE TITLE
game ends prematurely on failed challenge

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#66]
On latest code, word was challenged when no letters in letter bag and game ended even though everyone had letters left.  See screenshot below:

![gameend](https://user-images.githubusercontent.com/20344426/201270557-f50bfd62-29ed-4081-a873-f41e5dcfee48.png)

**Comment by cdot** [comment]
Who issued the challenge? You?

**Comment by cdot** [comment]
Fix in 3.0.0 has been back-ported to master.
