### ISSUE TITLE
cannot find 'someletter' on [...]

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#67]
Usually get this once a game.  Believe it started happening after you added the code to obfuscate the racks:

![cannotfind](https://user-images.githubusercontent.com/20344426/201272662-e1ff2afd-e7dd-4e92-a34c-e7bb045505ce.png)

fail@.../js/browser/Platform.js:27:107
assert@.../js/browser/Playform.js:23:25
removeTile@...js/game/Rack.js:125:16
rackToBoard...Game.js:734:34
handle_TURN...game_ui.js:417:21

**Comment by cdot** [comment]
Do you have "Undo" enabled?

**Comment by cdot** [comment]
Fixed in 3.0.0 branch and back-ported to main. Please test 3.0.0 if you can!
