### ISSUE TITLE
Bot doesn't care about tiles removed after successfully challenged word

### ISSUE THREAD

**Issue by jmontane** [cdot/Xanado#69]
I was testing Xanado playing a game in Catalan language. Using xanado:latest docker and a bot player

After playing an illegal move (PEÇA, it's a good word, but forms BA, which is wrong), bot challenged my move, and then tiles were removed from the board. All right. But then bot played its word (PAPERS) in a place using previously removed P tile, as it was still at board!!? Clearly, it's a bug.

Screenshot with issue
![bad-word-played](https://user-images.githubusercontent.com/339645/204628704-a18dc6d6-340b-4916-8047-e6ba2b84c258.png)

Game data file, with .log extension added
[aa9a4997cbb30180.game.log](https://github.com/cdot/Xanado/files/10116622/aa9a4997cbb30180.game.log)

**Comment by cdot** [comment]
There's no record of a challenge in the .game file, or in the log in your screenshot; PAPERS was a valid play after PEÇA, as far as I can see. BA appears in your dictionary (DISC_Catalan).

Having said that, the display is clearly messed up. I will see if I can reproduce it on the latest code.

**Comment by cdot** [comment]
I was able to reproduce this. It's something to do with the manual typing cursor. Will investigate.

**Comment by cdot** [comment]
That should have fixed it.

**Comment by jmontane** [comment]
You are right. I was wrong about the issue (BA is a recently added word). Sorry for confusion.
Thank you for your quick support.
