### ISSUE TITLE
board reveals when player has blank

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#70]
I couldn't get the latest master or 3.0 to work (will open separate report) so had to revert to 2.1.3.  Don't know if this has been fixed, but when a player has the blank in their hand and I believe maybe shuffles or moves a different tile to where the blank is in the rack (this may or may not be necessary), then plays non-blanks on the board, a letter may show with the green border indicating the player has the blank in their hand.  Screenshot below with a real blank and a non-blank (M) showing the border.  Believe this is due to the obfuscation code you added:

![blanks](https://user-images.githubusercontent.com/20344426/205223462-de527bca-abb7-434c-a84a-4fce48489cc3.png)

**Comment by cdot** [comment]
I very much doubt this has anything to do with the obfustication code, which only works on tiles in the rack. This appears to be something quite different. I'm not sure what steps are required to reproduce "may show up" but if you see this in the 3.0.0 code, please open this again.

**Comment by pkolano** [comment]
This is still happening in the latest v3/master code.  Still am speculating this is due to rack obfuscation (I thought that's when it started happening as well).  Namely, some part of the code is showing the tile where the blank was at some point in the rack even though it's not the blank.  Maybe that's not how it works, but would be my guess.  To reproduce, if you get a blank in your hand, hit the shuffle button a few times and play the non-blanks and the green box should show to one of the players (we usually play games of 4 and at least 2 of the other players always see the same tile with the green box).

![greenbox](https://user-images.githubusercontent.com/20344426/206628283-490b927a-13d0-4449-bd94-995b64338511.png)

**Comment by cdot** [comment]
Possibly a CSS class is sticking to the square. I will investigate.

**Comment by cdot** [comment]
It was indeed a CSS class sticking where it shouldn't have stuck. It didn't really reveal anything useful to other players, but wasn't useful, either.
