### ISSUE TITLE
tile swap no longer works

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#72]
In the latest v3, tile swap no longer works.  It just returns the letters to your hand when you hit swap.  Also, commented on #70 that it still exists (sorry, thought there would be the option to reopen, but I guess not).

**Comment by cdot** [comment]
It seems to work for me, on the standalone version anyway. Maybe something to do with your client? Please try it here: https://cdot.github.io/Xanado/dist/html/standalone_games.html and I will try it on the server version when I get home.
