### ISSUE TITLE
Error on game page

### ISSUE THREAD

**Issue by exander77** [cdot/Xanado#81]
On new version, if I create new game, add bot, join game, then after refresh I get this empty error message (might be bug by itself):

![image](https://user-images.githubusercontent.com/2256039/210101002-c408a9b0-3df4-4ef5-976c-8e0ad7438f8b.png)

Then console in Chrome shows:
```
UI.js:52 REPORT TypeError: Cannot read properties of undefined (reading 'email')
    at ClientGamesUI.js:312:11
    at Array.reduce (<anonymous>)
    at ClientGamesUI.showGames (ClientGamesUI.js:306:19)
    at Object.<anonymous> (GamesUIMixin.js:240:27)
    at mightThrow (jquery.js:3766:29)
    at process (jquery.js:3834:12)
```

```
          return em || game.getPlayerWithKey(game.whosTurnKey)
          .email;
```

Most likely because `game.whosTurnKey` is `undefined`.

**Comment by exander77** [comment]
Fixed the error message: https://github.com/cdot/Xanado/pull/80

It does it on unknown translations (like JS errors).

**Comment by cdot** [comment]
Yeah, the reporting was pretty crappy. It's somewhat improved in 3.1.0 but still could be better.
