### ISSUE TITLE
Cannot enter national character using keyboard if they are not single key

### ISSUE THREAD

**Issue by exander77** [cdot/Xanado#82]
Some national characters don't have a special key and instead, key for `'` or `ˇ` (and more on different languages) are used as switch, for example `ď.` If the key exists, the key does work, for example `í`, but I cannot input `í` as `'` and `i`.

**Comment by cdot** [comment]
Not being a user of (non-ASCII) national characters I have no idea where to start to fix this. :-(

**Comment by exander77** [comment]
@cdot I suspected as much, I will debug it myself and fix it.

**Comment by cdot** [comment]
From my reading, there is no standard for entering international characters, it has to be customised on a per-platform basis.
* Windows uses ALT+0123.
* X uses different methods, but the one most used for western languages is AltGR (altgr-intl keyboard in XKB).
* Gnome apparently supports a compose key (usually right-ctrl?) + some sequence of letters, but I couldn't get it to work.
* Individual apps / window managers might do something different.
Anyway, as far as the chat window is concerned, it it simply a standard HTML "input" element, so entering international characters there is a problem for the browser, not for Xanado.
When it comes to typing international characters from the rack, an approach might be to use the numbers (1-7) as proxies for the actual rack tile.

See also #93 regarding using the swap rack from the keyboard.

**Comment by exander77** [comment]
@cdot This is not really an issue.

There are two primary ways how to enter national characters.

Most national characters on most national keyboards are available as ready to use keys. So there is no need for such shenanigans. For example in Czech language, all national characters except ď, ť, ň are available like that.

The second way is to use a "spike key" pressed before a key:
`´` causes `d`, `t` to become `ď`, `ť`
`ˇ` causes `n` to become `ň`

But even in the second case, I think the key code produces in JS behaves like in the first case. So this is completely hidden JS. Btw, I think the ALT+0123 also works out of the box, it should produce correct key code in JS.

The chat Windows is not an issue, chat works, this is all handled in the OS. The issue is selecting a tile that goes on the board.

**Comment by cdot** [comment]
OK, so using the number keys as proxies for the rack tiles should suffice. I noticed a couple of other gotchas regarding use of the swap rack that I have fixed at the same time. Fixed on master branch (and will release in 3.2.0)
