### ISSUE TITLE
Windows sizing bug

### ISSUE THREAD

**Issue by exander77** [cdot/Xanado#83]
https://github.com/cdot/Xanado/pull/80/commits/a512c75745143148fdcf963aae23d54b81850858

It causes windows to go beyond the device width boundary. It is fixed in my pull.

**Comment by exander77** [comment]
But even with this fix, it is not that good:

![image](https://user-images.githubusercontent.com/2256039/210108808-2d7f408f-c79b-42a5-8fed-591c44c72eba.png)

**Comment by exander77** [comment]
I improved the tile resizing calculation.

![image](https://user-images.githubusercontent.com/2256039/210109982-57f22285-9e89-41f8-b76c-4d2e60b1121d.png)

**Comment by cdot** [comment]
Yup, that looks a lot better. I merged your pull request to master.

**Comment by exander77** [comment]
@cdot It looks fairly usable, but I know what is missing, I think I will improve it by decreasing the corner rounding with size as well.

**Comment by cdot** [comment]
OK, thanks @exander77. I will re-open this issue while you are working on it.

**Comment by cdot** [comment]
No further updates from exander77, so closing.
