### ISSUE TITLE
github pages publishing step is clumsy

### ISSUE THREAD

**Issue by cdot** [cdot/Xanado#88]
The action used to publish to github pages is an off-the-shelf action that doesn't seem to offer any way to customise it - I'd like to put in a `npm run build` step so I can do away with the checked-in `dist`.

**Comment by warren-bank** [comment]
you might want to add a new npm script that can be called as a one-off..
to update the git reference (hash) for the 'gh-pages' branch to be even with the HEAD of 'master':
```bash
git branch -f gh-pages master
```

though I wouldn't recommend this..
you _could_ add a git hook to automatically perform this action each time you add any commit:
```bash
echo '#!/bin/sh
git branch -f gh-pages master' > .git/hooks/post-commit
chmod u+x .git/hooks/post-commit
```

**Comment by cdot** [comment]
I worked out a suitable action.
