### ISSUE TITLE
Host a public server on totalvu

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#89]
Hi Crawford and all,

We'd like to host a publicly available server for this repo. I read somewhere that was a wish.
Currently, we have an older build with a customized UI running on https://esports1.totalvu.live/words.
If this seems like an OK idea from the project owner and community, we'd like to work together to get it up and running well.

**Comment by cdot** [comment]
I have no problem with you doing that, subject of course to acknowledgement of the source (a link back the the github page would be fine for that). I'm interested to know what "customised UI" means, as the project UI has been a bit of a moving target and is a lot slicker (and more robust) than previous releases.

**Comment by gwhizoftv** [comment]
Crawford, OK great. A link/banner sounds perfect.
Regarding customized UI, we followed your docs and then the advice you gave
via email to make small changes to colors,
images etc, as can be seen on the website. It will be great to see the
improvements to the UI since then.
The main issue will be getting the social logins working and setting up the
user database.

**Comment by cdot** [comment]
Not long ago I collapsed the CSS so you should be able to do all your customisation in a single file. At the same time I added support for user-selectable jQuery themes - grep for jquerytheme / jqtheme and it should be fairly obvious.
