### ISSUE TITLE
this.db is not iterable

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#9]
Greetings!  I've been successfully using the hanshuebner version for awhile, so was very interested to see you made a version with improvements and bug fixes for things that were definitely noticed while using that version (although it is still great and playable as is).  I ran "npm install" without issue and created "config.json" with basic settings:

{
    "port": 9093,
    "baseUrl": "http://localhost:9093/",
    "defaultEdition": "English_Scrabble",
    "defaultDictionary": "CSW2019_English",

    "auth": {
        "sessionSecret": "cross words",
        "db_file" : "passwd.json"
    }
}

When I try to run server.js, however, I get the following exception when I try to "sign up":

static files from /home/nodejs/Xanado-master/
Strings from /home/nodejs/Xanado-master/i18n/en.json
POST /register
Command rejected TypeError: this.db is not iterable
    at UserManager.genKey (/home/nodejs/Xanado-master/js/server/UserManager.js:359:24)
    at UserManager.addUser (/home/nodejs/Xanado-master/js/server/UserManager.js:395:21)
    at /home/nodejs/Xanado-master/js/server/UserManager.js:432:10 TypeError: this.db is not iterable
    at UserManager.genKey (/home/nodejs/Xanado-master/js/server/UserManager.js:359:24)
    at UserManager.addUser (/home/nodejs/Xanado-master/js/server/UserManager.js:395:21)
    at /home/nodejs/Xanado-master/js/server/UserManager.js:432:10

Do I have to initialize the passwd.json file somehow?  Also, does it have to be an absolute path or will it be relative to the main directory?  I tried both relative and absolute and tried creating a dummy file, but always seemed to get the same error.  Anyway, please let me know how to fix as my family and I are anxious to try out your improvements.  Thanks!

**Comment by jlbribeiro** [comment]
Hi @pkolano; I had the same issue as you. Just initialize the `db_file` with an empty array (`[]`).

(There's a different issue right now regarding user creation, which won't allow you to create valid users for the local (non-OAuth2) auth strategy; I'll be raising it in a moment.)

**Comment by pkolano** [comment]
Thank you, that worked (think I may have tried curly brackets initially).  Thanks also for #10 fix!
