### ISSUE TITLE
client_games.html bad location and infinite xanado animation on ipads

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#95]
In I believe 3.10 and above, in src/server/Server.js there is a conditional that uses either "html" or "dist" in two places.  It seems to use dist by default, which causes an error message about missing client_games.html and no way to load the game.

Also, I believe starting with either 3.12 or 3.14, there is something that is causing the first historical game screen to not load on ipads (any browser - safari, firefox, chrome).  It just shows the animated xanado indefinitely.  I reverted to 3.10 and the problem is not there so it is some change that was made.  Thanks

**Comment by cdot** [comment]
html or dist; that's right, it assumes that if you haven't enabled "debug" then you want to use the distribution, which has to be explicitly built:
``````
$ npm run build
'''
It would be smarter to use the "production" tag / environment variable introduced by webpack during the build process. I will investigate that.

Unfortunately I don't have an iPad (or any other demonic devices) so can't test. If any of the browsers allows you to open a console (More Tools -> <Web> Developer tools) then there should be some information output there. Please also put `?debug` at the end of the URL e.g. https://cdot.github.io/Xanado/dist/standalone_games.html?debug

Most likely explanation is case sensitivity in filenames, but I can't debug it further without the console output.

**Comment by pkolano** [comment]
I have been using an infinite shell while loop to keep the server running since at least in earlier versions, there would be crashes and I'm not always around when my family plays on my server.  If you use the run build, is there something that will restart on crash?

yes, agreed on apple products, but unfortunately, that's all my Mom has so don't have a choice.  I was seeing various exceptions in the output, but not sure if that is really for the game or if it was during parsing the previous game files as there have been issues there (possibly from games played on versions with end game bugs) where some complete games still show up in the games list.  These are the two types I see:

LOCK FAILURE bda57dd45b7f2124 Error: Lock file is already being held
    at /home/nodejs/Xanado-master/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/home/nodejs/Xanado-master/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:192:5) {
  code: 'ELOCKED',
  file: '/home/nodejs/Xanado-master/games/bda57dd45b7f2124.game'
}
Failed to load bda57dd45b7f2124 Error: 36ztocgyjd
    at Object.added (file:///home/nodejs/Xanado-master/src/game/Game.js:27:25)
    at r.encodeKey (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:11124)
    at file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:8912
    at Array.filter (<anonymous>)
    at c.encodeItem (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:8880)
    at c.encodeItem (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:9043)
    at c.encodeItem (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:8725)
    at c.encodeItem (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:9043)
    at c.encodes (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:9108)
    at c.encode (file:///home/nodejs/Xanado-master/node_modules/@cdot/cbor/dist/mjs/index.js:2:9222)

I will try to collect some info on the kids school ipads if I get a chance, but can't leave the new version running or my Mom can't play.

**Comment by cdot** [comment]
You only need to `run build` after a `git pull`. You might find it easier to run the Docker build for the family server, as it's already done for you.

The lock failure can safely be ignored, I don't know why it does it (3rd party module), but it doesn't seem to affect anything.

The load failure is mysterious. Can you let me have `games/bda57dd45b7f2124.game` ?

**Comment by cdot** [comment]
I now have a BrowserStack test account, so have been able to test on Safari. Unfortunately it doesn't support importmap, which is standard on every other browser. I can't see any approach that will support Safari without them.

**Comment by cdot** [comment]
Found a solution, now need to test on all the different platforms.

**Comment by cdot** [comment]
I changed the server command-line options so you can switch back to using the non-dist code easily using `--html html`. Performance will suffer, though not too much.

I've listed the tested browser versions in the README. It might be possible to push this further back, but it would be a lot of work that I'm not keen to undertake.

If anyone has an iPad or iPhone  (or other device from the nether regions) please test and please report the browser and iOS version numbers if it doesn't work.

**Comment by cdot** [comment]
No feedback, so I have to assume this is all OK now.
